name: Build Test Project

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  build:
    name: Build on ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install arm-none-eabi-gcc (Ubuntu)
      if: inputs.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi
      
    - name: Install arm-none-eabi-gcc (macOS)
      if: inputs.os == 'macos-latest'
      run: |
        brew install --cask gcc-arm-embedded
      
    - name: Install arm-none-eabi-gcc (Windows)
      if: inputs.os == 'windows-latest'
      run: |
        choco install gcc-arm-embedded -y
      
    - name: Configure CMake
      run: |
        cd test
        cmake -S .  -B build --toolchain=../../gcc/arm-none-eabi/cortex-m0.cmake -G 'Unix Makefiles'

    - name: Build
      run: |
        cmake --build test/build