name: Build on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test:
    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest